version: "3"
services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
